## GET request to example server
#GET localhost:5050/api/feature1/TokenEncode
#GET localhost:5050/api/feature2/DecodeToken
#GET localhost:5050/api/sendEmail
#GET localhost:5050/api/feature4/Profile
#GET localhost:5050/api/feature5/MyCookies
GET localhost:5050/api/feature6/CookieRemove